version: '3.8'
services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillforgeacademy
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres_data: