export * from './home';
export * from './index';
export * from './login';
export * from './login/styled-components';
export * from './register';
export * from './register/styled-components';
export * from './register/successfulRegister';
export * from './register/verification';
export * from './view-course';
